# Generated by Django 4.2.4 on 2023-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_publisher_remove_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
