# Generated by Django 4.2.4 on 2023-08-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_alter_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ganre',
            new_name='genre',
        ),
    ]
