# Generated by Django 4.2.4 on 2023-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0007_book_is_deleted_alter_publisher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
