# Generated by Django 4.2.4 on 2023-08-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0013_comment_user_alter_comment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
