# Generated by Django 4.2.4 on 2023-08-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0018_alter_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='books_app.book'),
        ),
    ]
